header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Webb Technologies Inc.

  paths-ignore:
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '.gitignore'
    - '.dockerignore'
    - '.editorconfig'
    - '.gitmodules'
    - '**/*.yml'
    - '**/*.json'
    - '**/*.lock'
    - '**/*.toml'
    - '**/*.yaml'
    - '.husky/*'
    - 'dkg-test-suite/protocol-solidity-fixtures/*'
    - '.nvmrc'
    - 'jest.config.js'
    - '**/*.sh'
    
  comment: on-failure