name: Code Coverage

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  coverage:
    name: Cover
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Install apt dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y clang libssl-dev llvm libudev-dev libgmp3-dev && \
          sudo rm -rf /var/lib/apt/lists/*

      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Run Tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--out Xml -p pallet-dkg-metadata -p pallet-dkg-proposal-handler -p pallet-dkg-proposals -p dkg-primitives -p dkg-runtime-primitives --locked --jobs 16 --timeout 3600 --skip-clean -- --test-threads 16 '

      - name: Upload CodeCov
        uses: codecov/codecov-action@v2

   

