name: dkg-test-suite

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test-code:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    # Enable this for clippy linting.
    # - name: Check and Lint Code
    #   run: cargo +nightly-2020-05-07 clippy -- -D warnings

    - name: Set up dkg node
      run: | 
        sh ./scripts/run-standalone.sh
      # Time out is in place to allow keygen to complete; unfortunatley non-deterministic    
    - name: Run anchor tests
      run: |
        timeout-minutes 1
        cd ./dkg-test-suite
        yarn anchor-proposals