name: Publish Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish_docs:
    # if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    name: Publish Documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Install Rust
        run: rustup update beta && rustup default beta

      - name: Update apt repositories
        run: sudo apt update

      # - name: Install OpenCL
      #   run: sudo apt install ocl-icd-opencl-dev

      - name: Build documentation
        run: cargo doc --no-deps --all-features
      - name: Publish documentation
        run: |
          cd target/doc
          git init
          echo '<meta http-equiv="refresh" content="0; url=https://dutterbutter.github.io/dkg-substrate/dkg-primitives/index.html">' > index.html
          git add .
          git -c user.name='ci' -c user.email='ci' commit -m 'Deploy documentation'
          git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages