name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test-code:
    name: ${{ matrix.make.name }} (${{ matrix.os }})
    # Set up matrix for future os test checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
      # Only running tests and checks for ubuntu right now
        os: [ubuntu-latest, macos-latest]
        # Only using nightly toolchain
        rust: [stable, beta, nightly]
        # Setup to execute cargo check, fmt, and make use of nextest run for unit tests
        make:
          - name: Check code
            task: "check"
          - name: Check Format
            task: "fmt --all -- --check"
          - name: Test Code
            task: "nextest run --verbose --workspace --all-features"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install cargo-nextest
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-nextest
        version: latest

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
    # Preserve directories between job runs
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    # Runs actual checks, fmt, and tests  
    - name: ${{ matrix.make.name }}
      run: cargo ${{ matrix.make.task }}

  miri-test:
    name: Test with miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: miri
      - run: cargo miri test --verbose --no-default-features
      - run: cargo miri test --verbose --all-features