name: Test Code

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test-code:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

      # Steps taken from https://github.com/actions/cache/blob/master/examples.md#rust---cargo
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly

    # Enable this for clippy linting.
    # - name: Check and Lint Code
    #   run: cargo +nightly-2020-05-07 clippy -- -D warnings

    - name: Check Code
      run: cargo check

    - name: Check Format
      run: cargo fmt --all -- --check

    - name: Build project
      env:
        RUSTC_BOOTSTRAP: '1'
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort'
      run: cargo build -p dkg-standalone-node

    - name: Test Code
      env:
        RUSTC_BOOTSTRAP: '1'
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort'
      run: cargo test -p dkg-standalone-node

    - name: Install Grcov
      run: cargo install grcov

    - name: Generate Coverage
      run: grcov . -s . --binary-path ./target/debug/ --ignore "target/debug/build/*"  -t html --branch --ignore-not-existing -o ./target/debug/coverage/
